### ISSUE TITLE
[oxygen] CentOS 6 failing state runner integration test

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#786]
- integration.runners.test_state.StateRunnerTest.test_orchestrate_retcode
```
Traceback (most recent call last):
  File "/testing/tests/integration/runners/test_state.py", line 193, in test_orchestrate_retcode
    self.assertIn(result, ret)
AssertionError: u'          ID: test_runner_success\n    Function: salt.runner\n        Name: runtests_helpers.success\n      Result: True' not found in u'Process took more than 60 seconds to complete. Process Killed!'
```
https://jenkins.saltstack.com/job/Oxygen/job/oxygen-salt-cent6-py2/lastCompletedBuild/testReport/

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/45658

**Comment by rallytime** [comment]
Hrm, this is still failing on CentOS 6: https://jenkins.saltstack.com/job/Oxygen/job/oxygen-salt-cent6-py2/lastFailedBuild/

**Comment by rallytime** [comment]
@terminalmage ^

**Comment by DmitryKuzmenko** [comment]
Ok, I've reproduced a failure in Docker. At least now I'm having the same test result. Analyzing this.

**Comment by Ch3LL** [comment]
closing this as it is not failing anymore on 2018.3. in fact all tests on cent6 are passing
