### ISSUE TITLE
Fedora 26 is not bootstrapping

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#794]
I am seeing this on
- 2016.11
- 2017.7 PY2
- 2017.7 PY3
- Oxygen PY2
- Oxygen PY3

On 2017.7.3 PY 2, there is an error, but it's different and related to the initial salt-cloud command:
```
12:30:30 Traceback (most recent call last):
12:30:30   File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1288, in create
12:30:30     output = self.clouds[func](vm_)
12:30:30   File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/linode.py", line 504, in create
12:30:30     'check_running': False})
12:30:30   File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/linode.py", line 271, in boot
12:30:30     if not _wait_for_job(linode_id, boot_job_id):
12:30:30   File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/linode.py", line 1550, in _wait_for_job
12:30:30     if jobs_result[0]['JOBID'] == job_id and jobs_result[0]['HOST_SUCCESS'] == 1:
12:30:30 KeyError: 0
```

The rest of the builds I checked are OK.

@dubb-b Can you look into this?

**Comment by dubb-b** [comment]
2016.11 [x]
2017.7 PY2 
2017.7 PY3
Oxygen PY2
Oxygen PY3

**Comment by dubb-b** [comment]
@rallytime The last build on Oxygen py3 timed out becuase of a pip package. I started another but its going to be a while before it kicks off. The build #84 I fixed yesterday seemed to work.

**Comment by rallytime** [comment]
Thanks @dubb-b I just checked and it looks like 2016.11 is still not bootstrapping and then develop for PY2 as well. (though that was passing yesterday so it wasn't on the list...hrm.)

**Comment by rallytime** [comment]
I am not as concerned about these presently as I am the others for releases, but still something to fix up and look at.

**Comment by dubb-b** [comment]
https://jenkins.saltstack.com/job/2016.9/job/salt-2016_9-linode-fedora26/198/console
2016.11 needed pip-based. I added, and also to develop. Will validate them all and test them when they free up and build.

**Comment by dubb-b** [comment]
https://jenkins.saltstack.com/job/develop/job/salt-linode-fedora26-develop/305/console

This one passed now.

**Comment by rallytime** [comment]
Thanks @dubb-b!
